### ISSUE TITLE
VL specificities list

### ISSUE THREAD

**Issue by CMath04** [metadata101/dcat-ap.vl#6]
- flag all specificity 
- discuss how to extract them

**Comment by CMath04** [comment]
# Todos

- [x] Update XSD to complies with https://joinup.ec.europa.eu/sites/default/files/distribution/access_url/2020-06/e4823478-4458-4546-9a85-3609867ad089/DCAT_AP_2.0.1.pdf, taking into accounts GeoNetwork needs and XML limitations when compared to RDF
- [ ] Update the config-editor & update-fixed-info to ensure XSD valid metadata can be edited
- [ ] Add missing thesauri & change VL specific thesauri if needed
- [ ] Create a Generic metadata template for dataset and for service
- [ ] (optional): Improve editor experience
- [ ] Update the indexing process to omit removed elements from the XSD
- [ ] Missing point ?
